[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.install]
cmds = ["mvn dependency:go-offline"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -jar target/*.jar"